interface Props {
  facilityName: string;
  reportDate: string;
  dateRange: { from: string; to: string };
  overallRisk: "LOW" | "MEDIUM" | "HIGH";
  summaryText: string;
  complianceRate: number;
  totalSamples: number;
}

function getRiskStyle(risk: string) {
  switch (risk) {
    case "HIGH":
      return "bg-red-100 text-red-700 border-red-300";
    case "MEDIUM":
      return "bg-amber-100 text-amber-700 border-amber-300";
    default:
      return "bg-emerald-100 text-emerald-700 border-emerald-300";
  }
}

export default function ExecutiveConclusion({
  facilityName,
  reportDate,
  dateRange,
  overallRisk,
  summaryText,
  complianceRate,
  totalSamples,
}: Props) {
  return (
    <section id="conclusion" className="space-y-6">
      <h2 className="text-xl font-bold text-slate-800 border-b pb-2">
        7. Executive Conclusion
      </h2>

      <div className="bg-white border border-slate-200 rounded-xl p-6 space-y-6">
        {/* Overall Risk */}
        <div className="flex items-center gap-4">
          <span className="text-sm text-slate-600">Overall Risk Assessment:</span>
          <span
            className={`text-sm px-3 py-1 rounded-full font-bold border ${getRiskStyle(overallRisk)}`}
          >
            {overallRisk}
          </span>
        </div>

        {/* Summary */}
        <div className="bg-slate-50 rounded-lg p-4">
          <p className="text-sm text-slate-700 leading-relaxed">{summaryText}</p>
        </div>

        {/* Key Stats */}
        <div className="grid grid-cols-3 gap-4 text-center">
          <div>
            <div className="text-2xl font-bold text-slate-900">
              {totalSamples}
            </div>
            <div className="text-xs text-slate-500">Total Samples</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-emerald-600">
              {complianceRate}%
            </div>
            <div className="text-xs text-slate-500">Compliance Rate</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-slate-900">
              {dateRange.from} – {dateRange.to}
            </div>
            <div className="text-xs text-slate-500">Reporting Period</div>
          </div>
        </div>

        {/* Signature Block */}
        <div className="border-t border-slate-200 pt-6 mt-6">
          <div className="grid grid-cols-2 gap-8">
            <div>
              <div className="border-b border-slate-300 pb-8 mb-2" />
              <p className="text-xs text-slate-500">
                Prepared by: EM Department
              </p>
              <p className="text-xs text-slate-400">Date: {reportDate}</p>
            </div>
            <div>
              <div className="border-b border-slate-300 pb-8 mb-2" />
              <p className="text-xs text-slate-500">
                Approved by: Quality Assurance
              </p>
              <p className="text-xs text-slate-400">Date: ___________</p>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="text-center text-xs text-slate-400 print:mt-8">
        <p>{facilityName} — Environmental Monitoring Manager Report</p>
        <p>Generated by Magnus EM on {reportDate}</p>
      </div>
    </section>
  );
}
